@startuml
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

title Summary\n

|#Lavender|User|
|#Plum|Recibo App|
|#Thistle|Database|
'|User|
'|Recibo App|
'|Database|

|User|
start
    :Click View Summary;
    :Select Month;

|Database|
    #Pink:Retrieve data for\nthe month selected;
|Recibo App|
    #APPLICATION:Generate summary\nof all receipts;
    #APPLICATION:Display Sumary;

stop
@enduml