@startuml

|User|
|Application|
|Database Server|
|User|
title Get Receipt Digitally
start

    |User|
    #Application:Log In;
    #Application:Click "Scan QR code";
    |Application|
    #pink:Loads camera to scan QR code;
    |User|
    #Application:Use app to scan QR code;
    |Database Server|
    #Lavender:Receipts are sent to the
    database server;
    |Application|
    #pink:App retrieves receipt for user;
    |User|
    #Application:User now has access to the receipt;

stop
@enduml