@startuml
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

|#Lavender|User|
|#Plum|Recibo App|
|#Thistle|Database|
|User|
title Get Receipt Digitally
start

    |User|
        :Log In;
        :Click "Scan QR code";
    |Recibo App|
        #Application:Loads camera to scan QR code;
    |User|
        :Use app to scan QR code;
    |Database|
        #Pink:Receipts are sent to the
        database server;
    |Recibo App|
        #Application:App retrieves receipt for user;
    |User|
        :User now has access to the receipt;

stop
@enduml