@startuml
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

|#Lavender|User|
|#Plum|Recibo App|
|User|

title Sort Receipts
start
    |User|
        :Log in;
        :Click sort receipt button;
    |Recibo App|
        #Application:if (Display the sort category options) then
            #Application:Sort by date;
        else
            #Application:Sort by store's name;
        endif;

    |User|
        :Chooses the category;
    |Recibo App|
        #Application:Receipts are sorted and displayed
     based on the sort category;

stop
@enduml