@startuml

class Server <<singleton>> {
    -String authToken
    getConnection()
    sync()
}

class Account {
    authenticate()
    createUser()
    resetPassword()
    deleteAccount()
}
Server <.. Account

class User {
    String username
    sendReceipt(Receipt)
}

class ReceiptCode {
    -String code
    downloadReceipt()
}

class ReceiptWallet {
    Receipt search(String query)
    addCategory()
    addReceipt(ReceiptCode code)
}
SearchStrategy <.. ReceiptWallet
ReceiptCode <.. ReceiptWallet

class Category {
    -name
    List<Receipt> listReceipts()
    addReceipt(Receipt)
}

class Receipt {
    String receiptId
    String path
}

class MonthlySummary {
    Date monthStart
    getTotal()
    generateChart()
}

class FriendsList {
    listFriends()
    sendFriendRequest()
}

class SharingDialog {
    generatePDF(Receipt)
    share()
    export()
    print()
}
FriendsList <.. SharingDialog

class ReceiptScanner {
    scanReceipt()
    decodeReceipt()
}
Server <.. ReceiptScanner

class Notification {
    pushNotification()
}

class SortStrategy {
int compare(Receipt a, Receipt b)
}

class SortByDate {
int compare(Receipt a, Receipt b)
}
SortStrategy <|== SortByDate

class SortByCategory {
int compare(Receipt a, Receipt b)
}
SortStrategy <|== SortByCategory

class SortByMerchant {
int compare(Receipt a, Receipt b)
}
SortStrategy <|== SortByMerchant

class Page {

}

class LaunchPage {

}
Page <|== LaunchPage

class SignUpPage {

}
Page <|== SignUpPage
Account <.. SignUpPage

class HomePage {

}
Page <|== HomePage

class LoginPage {

}
Page <|== LoginPage
Account <.. LoginPage

class SearchPage {
}
Page <|== SearchPage
SortStrategy <.. SearchPage

class AboutPage {
}
Page <|== AboutPage

class ProductPage {
}
Page <|== ProductPage

class ListReceiptsPage {
}
Page <|== ListReceiptsPage

class SortReceiptsPage {
}
Page <|== SortReceiptsPage

class GetReceiptPage {
}
Page <|== GetReceiptPage
ReceiptScanner <.. GetReceiptPage

class MonthlySummaryPage {
}
Page <|== MonthlySummaryPage
MonthlySummary <.. MonthlySummaryPage

@enduml
